package com.ershou.ershoumarket.dao;

import com.ershou.ershoumarket.dataobject.ItemDo;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface ItemDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Nov 03 14:23:35 GMT+08:00 2019
     */
    List<ItemDo> listItem();
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Nov 03 14:23:35 GMT+08:00 2019
     */
    int insert(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Nov 03 14:23:35 GMT+08:00 2019
     */
    int insertSelective(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Nov 03 14:23:35 GMT+08:00 2019
     */
    ItemDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Nov 03 14:23:35 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Nov 03 14:23:35 GMT+08:00 2019
     */
    int updateByPrimaryKey(ItemDo record);
}